[package]
name = "tsgo"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0-alpha", features = ["napi4"] }
napi-derive = { version = "3.0.0-alpha", default-features = false, features = ["type-def"] }

[build-dependencies]
napi-build = "2.1.5"
