/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function runProject(project: string): void

export declare function transform(input: string | Uint8Array, filename: string): string
