name: Node-API

on:
  push:
    branches:
      - main
  pull_request:
      
jobs:
  build:
    runs-on: ${{ matrix.settings.host }}
    strategy:
      matrix:
        settings:
          - target: aarch64-apple-darwin
            host: macos-latest
          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - run: npm install
      - run: npm run build:rust -- --target ${{ matrix.settings.target }} --use-napi-cross
        if: ${{ contains(matrix.settings.target, 'linux') }}
      - run: npm run build:rust -- --target ${{ matrix.settings.target }}
        if: ${{ !contains(matrix.settings.target, 'linux') }}
